[package]
name = "cc_cli"
version = "0.0.1"
authors = ["Rukai <rubickent@gmail.com>"]
description = "CLI client for PF Sandbox"
license = "GPL-3.0"
repository = "https://github.com/rukai/pf_sandbox"
keywords = ["pf", "sandbox", "CLI", "command", "client"]

[dependencies]
