language: rust
dist: xenial
rust:
  - stable
addons:
  apt:
    packages:
      - libssl-dev
      - libudev-dev
      - libgtk-3-dev
cache: cargo
# commented out as website is not running for now
#before_install:
#  - openssl aes-256-cbc -K $encrypted_6f89add0ca02_key -iv $encrypted_6f89add0ca02_iv
#    -in ssh-keys-travis.tar.enc -out ssh-keys-travis.tar -d
#install:
#  - rm -r ~/.ssh
#  - tar -xvf ssh-keys-travis.tar
#  - mv .ssh ~/.ssh
script:
  - "./travis.sh"
branches:
  only:
    - master
