language: rust
dist: bionic
rust:
  - stable
addons:
  apt:
    packages:
      - libssl-dev
      - libudev-dev
      - libgtk-3-dev
      #- blender # blender version on bionic is too old, so we need to manually download a newer version
cache: cargo
before_install:
  - openssl aes-256-cbc -K $encrypted_d92ccd3ac14c_key -iv $encrypted_d92ccd3ac14c_iv -in ssh-keys-travis.tar.enc -out ssh-keys-travis.tar -d

install:
  - rm -r ~/.ssh
  - tar -xvf ssh-keys-travis.tar
  - mv .ssh ~/.ssh
script:
  - "./travis.sh"
branches:
  only:
    - master
