environment:
  global:
    RUST_VERSION: stable
  matrix:
    - TARGET: x86_64-pc-windows-msvc

image: Visual Studio 2017

install:
  # setup ssh keys
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt ssh-keys-appveyor.zip.enc -secret %ssh-keys-secret%
  - 7z x ssh-keys-appveyor.zip
  - rm -r C:/Users/appveyor/.ssh
  - mv .ssh C:/Users/appveyor/

  # Setup gtk deps https://gtk-rs.org/docs-src/requirements.html
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - bootstrap-vcpkg.bat
  - vcpkg install gtk:x64-windows
  - set VCPKGDIR=%CD%\installed\x64-windows
  - set PATH=%VCPKGDIR%\bin;%PATH%
  - set GTK_LIB_DIR=%VCPKGDIR%\lib
  - mklink %VCPKGDIR%\lib\gtk-3.lib %VCPKGDIR%\lib\gtk-3.0.lib
  - mklink %VCPKGDIR%\lib\gdk-3.lib %VCPKGDIR%\lib\gdk-3.0.lib
  - mklink %VCPKGDIR%\bin\gtk-3.0.dll %VCPKGDIR%\bin\gtk-3.dll
  - mklink %VCPKGDIR%\bin\gdk-3.0.dll %VCPKGDIR%\bin\gdk-3.dll
  - mkdir %VCPKGDIR%\etc
  - mkdir %VCPKGDIR%\etc\gtk-3.0
  - echo "[Settings]" >> %VCPKGDIR%\etc\gtk-3.0\settings.ini
  - echo "gtk-theme-name=win32" >> %VCPKGDIR%\etc\gtk-3.0\settings.ini
  - cd ..
    # TODO: instructions say to add settings.ini file, but it doesnt look very important.
  # Setup shaderc deps
  - set PATH=C:\Python37;%PATH%
  - choco install ninja
  # Setup rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  - echo %PATH%

test_script:
  - cargo test --release --all
  - cargo build --release --all
  - mkdir cc
  - move target\release\canon_collision.exe cc
  - move target\release\cc_cli.exe cc
  - move target\release\cc_map_controllers.exe cc
  - move target\release\panic_handler.exe cc
  - 7z a canoncollision-%APPVEYOR_REPO_COMMIT:~0,15%-windows.zip cc
  # TODO: Need to fix knownhosts file first
  #- echo put canoncollision-%APPVEYOR_REPO_COMMIT:~0,15%-windows.zip /home/ubuntu/CanonCollisionWebsite/builds/ | sftp ubuntu@ec2-13-210-166-146.ap-southeast-2.compute.amazonaws.com

skip_tags: true
cache:
  - C:\Users\appveyor\.cargo\registry
# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
