[workspace]
members = [
    "canon_collision",
    "canon_collision_lib",
    "cc_cli",
    "map_controllers",
    "panic_handler",
    "runtime_state_upgrader"
]

[profile.release]
debug-assertions = true
