[workspace]
members = [
    "canon_collision",
    "canon_collision_lib",
    "canon_collision_hot_reload",
    "cc_cli",
    "map_controllers",
    "panic_handler",
    "package_upgrader",
    "generate_hurtboxes",
]
resolver = "2"

[profile.release]
debug-assertions = true
