[package]
name = "package_upgrader"
version = "0.0.1"
license = "GPL-3.0"
authors = ["Rukai <rubickent@gmail.com>"]
repository = "https://github.com/rukai/canon_collision"
edition = "2018"

[dependencies]
serde_cbor = "0.10"
canon_collision_lib = { path = "../canon_collision_lib" }
