[package]
name = "panic_handler"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]
edition = "2021"
rust-version = "1.56"

[dependencies]
gtk = "0.14"
canon_collision_lib = { path = "../canon_collision_lib" }
